apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: demo-golang
  labels:
    dockerdev: db
data:
  POSTGRES_DB: goland
  POSTGRES_USER: goland
  POSTGRES_PASSWORD: goland
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    dockerdev: db
  name: db
  namespace: demo-golang
spec:
  serviceName: dockerdev-db
  selector:
    matchLabels:
      dockerdev: db
  template:
    metadata:
      labels:
        dockerdev: db
    spec:
      containers:
        - name: db
          image: postgres:12.2-alpine
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: db-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-config
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-config
          persistentVolumeClaim:
            claimName: postgresql-pvc


---
apiVersion: v1
kind: Service
metadata:
  labels:
    dockerdev: db
  name: dockerdev-db-exported
  namespace: demo-golang
spec:
  type: LoadBalancer
  ports:
    - name: 5432-tcp
      port: 5432
      targetPort: 5432
  selector:
    dockerdev: db