apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: demo-golang
spec:
  capacity: 
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/postgresql/init
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: 
            - node2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: demo-golang
spec:
  volumeName: postgresql-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
