apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: demo-golang
  labels:
    app: web
spec:
  replicas: 1
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: bravopotato/docker-dev:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "dockerdev-db-exported"
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: web
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: demo-golang
spec:
  selector:
    app: web
  ports:
    - port: 8080
      targetPort: 8080
      name: web-app-port
  type: LoadBalancer